# Generated by Django 4.2.13 on 2024-09-10 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='rental.room'),
        ),
    ]
