# Generated by Django 4.2.13 on 2024-09-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('rental', '0003_billrentalcontact_bill_number_and_more'),
	]

	operations = [
		migrations.AddField(
			model_name='electricityandwaterbills',
			name='status',
			field=models.CharField(choices=[('PAID', 'Đã thanh toán'), ('UNPAID', 'Chưa thanh toán')], default='UNPAID', max_length=255),
		),
	]
