# Generated by Django 4.2.13 on 2024-09-11 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		('rental', '0001_initial'),
		('interacts', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='comment',
			name='post',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='rental.post'),
		),
	]
